---
- name: Nginx playbook
  hosts: webserver
  become: true
  pre_tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        file: vars.yml
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: Reload nginx
    - name: Copy nginx config
      ansible.builtin.copy:
        src: nginx.conf
        dest: "/etc/nginx/sites-enabled/{{ project_name }}"
        mode: '644'
      notify: Reload nginx config
    - name: Unlink default nginx
      ansible.builtin.command:
        cmd: unlink /etc/nginx/sites-enabled/default
        removes: /etc/nginx/sites-enabled/default
      notify: Reload nginx config
    - name: Import Python tasks
      ansible.builtin.include_tasks:
        file: tasks/python.yml
      when: project_language == 'python'
  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: true
    - name: Reload nginx config
      ansible.builtin.command:
        cmd: nginx -s reload
    - name: Reload supervisor
      ansible.builtin.service:
        name: supervisor
        state: reloaded
        enabled: true
